version: "3"
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000"
    image: "amazon/dynamodb-local:2.5.2"
    ports:
      - "8000:8000"
    working_dir: "/home/dynamodblocal"

  sequencer-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3002:3002"
    command: npm run start-dev
    depends_on:
      - dynamodb

  block-listener:
    build:
      context: dev-scripts/block-listener
      dockerfile: Dockerfile
    env_file: .env
    command: node index.js
    depends_on:
      - sequencer-monitor

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
