version: "3"
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000"
    image: "amazon/dynamodb-local:2.5.2"
    ports:
      - "8000:8000"
    working_dir: "/home/dynamodblocal"

  sequencer-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3002:3002"
    command: npm run start-dev
    depends_on:
      - dynamodb
