service: wonderland-challenge
app: notifier

provider:
  name: aws
  runtime: nodejs20.x

functions:
  notify-idle-maker-job:
    handler: src/notify-idle-maker-job.handler

plugins:
  - serverless-offline
