service: sequencer-monitor
app: sequencer-monitor
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    RPC_NODE_URL: ${env:RPC_NODE_URL}
    SEQUENCER_ADDRESS: ${env:SEQUENCER_ADDRESS}
    DYNAMODB_ENDPOINT_URL: ${env:DYNAMODB_ENDPOINT_URL}

functions:
  notify-unworked-jobs:
    handler: sequencer-monitor/notify-unworked-jobs.handler
    timeout: 30

plugins:
  - serverless-offline
  - serverless-plugin-typescript
